spring.application.name=NOVAEvents
spring.mvc.hiddenmethod.filter.enabled=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


spring.datasource.url=jdbc:mysql://localhost:3306/dbname
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always

jwt.secret=your-secret-key-must-be-at-least-32-characters-long
jwt.expiration-ms=86400000

weather.api.key=549e3c0521c3dd5144921536102de470